import Foundation

final class FinderProjectSyncService {

    private let nodeStore: NodeStore
    private let fileManager: FileManager
    private let rootURLProvider: () throws -> URL
    private let syncLock = NSLock()
    private var pendingSyncTask: Task<Void, Never>?

    init(
        nodeStore: NodeStore,
        fileManager: FileManager = .default,
        rootURLProvider: @escaping () throws -> URL = { try FinderProjectSyncService.defaultRootURL() }
    ) {
        self.nodeStore = nodeStore
        self.fileManager = fileManager
        self.rootURLProvider = rootURLProvider
    }

    func scheduleSync() {
        pendingSyncTask?.cancel()
        pendingSyncTask = Task.detached(priority: .utility) { [weak self] in
            try? await Task.sleep(for: .milliseconds(350))
            guard !Task.isCancelled else { return }
            self?.syncNow()
        }
    }

    func syncNow() {
        syncLock.lock()
        defer { syncLock.unlock() }

        do {
            try exportAllProjects()
        } catch {
            NSLog("FinderProjectSyncService sync failed: %@", error.localizedDescription)
        }
    }

    static func defaultRootURL() throws -> URL {
        guard let documentsURL = FileManager.default
            .urls(for: .documentDirectory, in: .userDomainMask)
            .first else {
            throw FinderProjectSyncError.documentsDirectoryUnavailable
        }

        return documentsURL.appendingPathComponent("Nous Finder Projects", isDirectory: true)
    }

    private func exportAllProjects() throws {
        let rootURL = try rootURLProvider()
        try fileManager.createDirectory(at: rootURL, withIntermediateDirectories: true)
        try clearDirectoryContents(at: rootURL)
        try writeText(readme(), to: rootURL.appendingPathComponent("README.md"))

        let projects = try nodeStore.fetchAllProjects()
        let allNodes = try nodeStore.fetchAllNodes()
        let nodesByProject = Dictionary(grouping: allNodes) { $0.projectId }

        for project in projects.sorted(by: sortProjects) {
            try exportProject(
                project,
                nodes: nodesByProject[project.id] ?? [],
                rootURL: rootURL
            )
        }

        let inboxNodes = (nodesByProject[nil] ?? []).sorted(by: sortNodes)
        if !inboxNodes.isEmpty {
            try exportBucket(
                title: "Inbox",
                description: "Nodes not attached to a project yet.",
                nodes: inboxNodes,
                rootURL: rootURL,
                bucketId: "inbox"
            )
        }
    }

    private func exportProject(_ project: Project, nodes: [NousNode], rootURL: URL) throws {
        try exportBucket(
            title: project.title,
            description: project.goal.isEmpty ? "No project goal saved." : project.goal,
            nodes: nodes.sorted(by: sortNodes),
            rootURL: rootURL,
            bucketId: project.id.uuidString,
            emoji: project.emoji,
            createdAt: project.createdAt
        )
    }

    private func exportBucket(
        title: String,
        description: String,
        nodes: [NousNode],
        rootURL: URL,
        bucketId: String,
        emoji: String? = nil,
        createdAt: Date? = nil
    ) throws {
        let folderName = "\(safeFileComponent(title, fallback: "Untitled")) [\(shortId(bucketId))]"
        let bucketURL = rootURL.appendingPathComponent(folderName, isDirectory: true)
        let notesURL = bucketURL.appendingPathComponent("Notes", isDirectory: true)
        let conversationsURL = bucketURL.appendingPathComponent("Conversations", isDirectory: true)

        try fileManager.createDirectory(at: notesURL, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: conversationsURL, withIntermediateDirectories: true)

        var summaryLines = ["# \(title)", ""]
        if let emoji, !emoji.isEmpty {
            summaryLines.append("Emoji: \(emoji)")
        }
        summaryLines.append("Bucket ID: \(bucketId)")
        if let createdAt {
            summaryLines.append("Created: \(format(createdAt))")
        }
        summaryLines.append("Exported: \(format(Date()))")
        summaryLines.append("")
        summaryLines.append(description)
        summaryLines.append("")
        summaryLines.append("Notes: \(nodes.filter { $0.type == .note }.count)")
        summaryLines.append("Conversations: \(nodes.filter { $0.type == .conversation }.count)")
        summaryLines.append("")
        summaryLines.append("This folder is generated by Nous for Finder browsing.")
        summaryLines.append("Edits here are overwritten on the next sync.")

        try writeText(summaryLines.joined(separator: "\n"), to: bucketURL.appendingPathComponent("Project.md"))

        for node in nodes {
            switch node.type {
            case .note:
                let fileURL = notesURL.appendingPathComponent(fileName(for: node), isDirectory: false)
                try writeText(renderNote(node), to: fileURL)
            case .conversation:
                let fileURL = conversationsURL.appendingPathComponent(fileName(for: node), isDirectory: false)
                let messages = try nodeStore.fetchMessages(nodeId: node.id)
                try writeText(renderConversation(node, messages: messages), to: fileURL)
            }
        }
    }

    private func renderNote(_ node: NousNode) -> String {
        var lines = [
            "# \(node.title)",
            "",
            "Node ID: \(node.id.uuidString)",
            "Type: note",
            "Created: \(format(node.createdAt))",
            "Updated: \(format(node.updatedAt))",
            "Favorite: \(node.isFavorite ? "yes" : "no")"
        ]

        if let emoji = node.emoji, !emoji.isEmpty {
            lines.append("Emoji: \(emoji)")
        }

        lines.append("")
        if node.content.isEmpty {
            lines.append("_Empty note._")
        } else {
            lines.append(node.content)
        }

        return lines.joined(separator: "\n")
    }

    private func renderConversation(_ node: NousNode, messages: [Message]) -> String {
        var lines = [
            "# \(node.title)",
            "",
            "Node ID: \(node.id.uuidString)",
            "Type: conversation",
            "Created: \(format(node.createdAt))",
            "Updated: \(format(node.updatedAt))",
            "Favorite: \(node.isFavorite ? "yes" : "no")",
            ""
        ]

        if messages.isEmpty {
            lines.append(node.content.isEmpty ? "_Empty conversation._" : node.content)
            return lines.joined(separator: "\n")
        }

        for message in messages {
            let heading = message.role == .user ? "User" : "Nous"
            lines.append("## \(heading) · \(format(message.timestamp))")
            lines.append("")
            lines.append(message.content.isEmpty ? "_Empty message._" : message.content)
            lines.append("")

            if let thinkingContent = message.thinkingContent,
               !thinkingContent.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                lines.append("### Thinking")
                lines.append("")
                lines.append(thinkingContent)
                lines.append("")
            }
        }

        return lines.joined(separator: "\n")
    }

    private func fileName(for node: NousNode) -> String {
        "\(safeFileComponent(node.title, fallback: defaultTitle(for: node))) [\(shortId(node.id.uuidString))].md"
    }

    private func defaultTitle(for node: NousNode) -> String {
        switch node.type {
        case .note:
            return "Untitled Note"
        case .conversation:
            return "Untitled Conversation"
        }
    }

    private func safeFileComponent(_ raw: String, fallback: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        let source = trimmed.isEmpty ? fallback : trimmed
        let space = " ".unicodeScalars.first!
        let dash = "-".unicodeScalars.first!
        let underscore = "_".unicodeScalars.first!
        let filteredScalars = source.unicodeScalars.map { scalar -> Character in
            if CharacterSet.alphanumerics.contains(scalar) || scalar == space || scalar == dash || scalar == underscore {
                return Character(String(scalar))
            }
            return "-"
        }

        let collapsed = String(filteredScalars)
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .replacingOccurrences(of: "-{2,}", with: "-", options: .regularExpression)
            .trimmingCharacters(in: CharacterSet(charactersIn: " -_"))

        let candidate = collapsed.isEmpty ? fallback : collapsed
        return String(candidate.prefix(60))
    }

    private func shortId(_ value: String) -> String {
        String(value.prefix(8))
    }

    private func sortProjects(lhs: Project, rhs: Project) -> Bool {
        lhs.title.localizedCaseInsensitiveCompare(rhs.title) == .orderedAscending
    }

    private func sortNodes(lhs: NousNode, rhs: NousNode) -> Bool {
        if lhs.updatedAt != rhs.updatedAt {
            return lhs.updatedAt > rhs.updatedAt
        }
        return lhs.title.localizedCaseInsensitiveCompare(rhs.title) == .orderedAscending
    }

    private func clearDirectoryContents(at url: URL) throws {
        let contents = try fileManager.contentsOfDirectory(
            at: url,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        )

        for childURL in contents {
            try fileManager.removeItem(at: childURL)
        }
    }

    private func writeText(_ text: String, to url: URL) throws {
        let data = Data(text.utf8)
        try data.write(to: url, options: .atomic)
    }

    private func format(_ date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter.string(from: date)
    }

    private func readme() -> String {
        [
            "# Nous Finder Projects",
            "",
            "This folder is regenerated by Nous.",
            "Each project is exported as a Finder-visible folder with Markdown files.",
            "Edits here are overwritten on the next sync."
        ].joined(separator: "\n")
    }
}

enum FinderProjectSyncError: LocalizedError {
    case documentsDirectoryUnavailable

    var errorDescription: String? {
        switch self {
        case .documentsDirectoryUnavailable:
            return "Could not locate the user's Documents directory."
        }
    }
}
